### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by Gribou**
Hi, 
First, great job.
Exactly what i'm looking for.
I want to use it for a raspberry 3.2' LCD. So I would like 2 little things : 
- How can i stop the information moving (screen is to small and it's blinking)
- Can you add  French option for the weather informations

have a nice day

### CODE REVIEW

**Comment by zhum** [comment]
Thank you for your pullrequest! Unfortunately I can't speak Franch, could you add the translation? I'm already thinking about real l10n via yaml files...

Stop-mode is planned, I'm thinking now about elegant theming.

**Comment by Gribou** [comment]
Hi,
no problem, i don't speak russian to :-)
here my translation, i do my best, hope it's good : 

 'francais' =>
    [
      ["tornade",""],
      ["tropical","orage"],
      ["ouragan",""],
      ["sérieux","orages"],
      ["orages",""],
      ["pluie et","neige mélée"],
      ["pluie et","neige fondue"],
      ["neige et","neige fondue"],
      ["gel","bruine"],
      ["bruine",""],

```
  ["gel","pluie"],
  ["averses",""],
  ["averses",""],
  ["neige","averse"],
  ["legeres chute de neige",""],
  ["tempête de neige",""],
  ["neige",""],
  ["grêle",""],
  ["neige fondue",""],
  ["poussiere",""],

  ["brumeux",""],
  ["brume",""],
  ["brouillard",""],
  ["tempête",""],
  ["Venteux",""],
  ["froid",""],
  ["couvert",""],
  ["nuageux",""],
  ["nuageux",""],
  ["partiellement nuageux",""],

  ["partiellement nuageux",""],
  ["clair",""],
  ["ensoleillé",""],
  ["beau",""],
  ["beau",""],
  ["pluie et grêle",""],
  ["chaud",""],
  ["orages isolés",""],
  ["orages épars",""],
  ["orages épars",""],

  ["pluies éparses",""],
  ["fortes chutes de neige",""],
  ["chutes de neiges éparses",""],
  ["fortes chutes de neige",""],
  ["partiellement nuageux",""],
  ["orages",""],
  ["chute de neige",""],
  ["orages isolés",""]
],
```

For the 'Stop-mode' i found a tips : put 

# speed of sliding in x and y direction

xspeed: 0
yspeed: 0
in rubysaver.conf 

I have also modify the rs.rb file and change the line : 
@x=@y=0
to 
@x=15
@y=40
For having a best screen displayed information (more center)

I have also modify the gifs files (reduce them by 2 , because i use a very small screen)

elegant theming could be a great idea :-) 

Have a nice day

**Comment by zhum** [comment]
I have added your translation and added 'stop_mode' - it turns off moving and centers the image.

Now I'm thinking about theming options... If you have any ideas, please write me :)

**Comment by Gribou** [comment]
Great, i'll test this asap.
for theming, unfortunately i'm not a design specialist :-) . but what would be cool is to put a little explaination of the 2nd et 3rd line of the screen, is it forecast ? May be it could be cool to have temperature forcast for the day and precipitations forecast too, like on the yahoo meteo web site.
But do you think that it's possible to have those informations turning on 3 seperate screens ?
Ok I stop ... :-)

**Comment by zhum** [comment]
Now picture is designed like this: first big line = current conditions, second (small) = today forecast, third (small) = tomorrow forecast.

For separate screens - I don't know how to to do this and cannot test... You can try to experiment with my code.

**Pull request merged**
